"""init

Revision ID: dd9f7cb17480
Revises: 
Create Date: 2025-08-03 21:30:33.275626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9f7cb17480'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captcha_chats',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('captcha_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('captcha_chats')
    # ### end Alembic commands ###
